# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


data = {
    'State': ['Andhra Pradesh', 'Telangana', 'Tamil Nadu',
              'Karnataka', 'Kerala', 'Maharashtra',
              'Delhi', 'Punjab'],

    'Unemployment Rate (%)': [7.5, 8.2, 6.1, 5.8, 9.0, 7.2, 10.5, 6.8],

    'Employed': [500000, 450000, 620000, 580000,
                 400000, 700000, 300000, 350000],

    'Labour Participation Rate (%)': [42.5, 44.2, 41.8,
                                      40.5, 39.7, 45.1,
                                      38.9, 41.2]
}


df = pd.DataFrame(data)

print("UNEMPLOYMENT DATASET\n")
print(df)
print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nStatistical Summary:")
print(df.describe())
plt.figure(figsize=(10,5))

sns.barplot(
    x='State',
    y='Unemployment Rate (%)',
    data=df
)

plt.title('State-wise Unemployment Rate')
plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(
    df['Unemployment Rate (%)'],
    kde=True
)

plt.title('Distribution of Unemployment Rate')

plt.show()

plt.figure(figsize=(8,5))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Heatmap')

plt.show()
highest = df.loc[
    df['Unemployment Rate (%)'].idxmax()
]

print("\nState with Highest Unemployment:\n")
print(highest)

print("\nConclusion:")
print("Delhi has the highest unemployment rate in this dataset.")
print("The project successfully analyzes unemployment data using Python.")

